object Compose {
    const val composeVersion = "1.4.6"
    const val composeUiVersion = "1.4.3"
    private const val composeBOMVersion = "2022.10.00"

    private const val material3Version = "1.1.1"
    private const val materialVersion = "1.4.3"
    private const val windowSizeClassVersion = "1.0.0-alpha10"
    private const val composeActivitiesVersion = "1.6.1"
    private const val composeNavigationVersion = "2.5.3"
    private const val composeCoilVersion = "2.2.2"
    private const val composeLifecycleVersion = "2.5.1"
    private const val composeFoundationVersion = "1.3.1"
    private const val sheetsComposeDialogsVersion = "1.1.0"


    const val composeBom = "androidx.compose:compose-bom:${composeBOMVersion}"
    const val runtime = "androidx.compose.runtime:runtime:${composeVersion}"
    const val ui = "androidx.compose.ui:ui:${composeUiVersion}"
    const val uiTooling = "androidx.compose.ui:ui-tooling:${composeUiVersion}"
    const val uiToolingPreview = "androidx.compose.ui:ui-tooling-preview:${composeUiVersion}"
    const val material = "androidx.compose.material:material:${materialVersion}"
    const val material3 = "androidx.compose.material3:material3:${material3Version}"
    const val windowSizeClass = "androidx.compose.material3:material3-window-size-class:${material3Version}"
    const val foundation = "androidx.compose.foundation:foundation:${composeFoundationVersion}"
    const val activity = "androidx.activity:activity-compose:${composeActivitiesVersion}"
    const val navigation = "androidx.navigation:navigation-compose:${composeNavigationVersion}"
    const val composeCoil= "io.coil-kt:coil-compose:$composeCoilVersion"
    const val composeLifecycle= "androidx.lifecycle.lifecycle-runtime-compose:$composeLifecycleVersion"
    const val composeDialogsCore = "com.maxkeppeler.sheets-compose-dialogs:core:$sheetsComposeDialogsVersion"
    const val composedateTimeDialogs = "com.maxkeppeler.sheets-compose-dialogs:date_time:$sheetsComposeDialogsVersion"
    const val composeCalendarDialogs = "com.maxkeppeler.sheets-compose-dialogs:calendar:$sheetsComposeDialogsVersion"
}